app/casshern/casshern/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^grid_creation/', include('grid_creation.urls', namespace="grid_creation")),
    url(r'^admin/', include(admin.site.urls)),
]

app/casshern/grid_creation/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'result/', views.result, name='result'),
]

app/casshern/grid_creation/models.py
from django.db import models

import sys
sys.path.insert(0, '/home/nestarz/Github/Mobile-Suit-Riders/src')

import instances
import main

# Create your models here.
class Grid(models.Model):
    line_size = models.BigIntegerField()
    column_size = models.BigIntegerField()
    obstacle_amount = models.BigIntegerField()
    pub_date = models.DateTimeField('date published')
    grid = []
    robot_pos = []
    path = []

    def generate(self):
        self.grid = instances.generate_grid(int(self.line_size),
                                            int(self.column_size),
                                            int(self.obstacle_amount))
        self.robot_pos, self.goal, self.robot_ori = instances.generate_robot(self.grid)

    def solve(self):
        graph = main.generateGraph(self.grid)
        self.path = graph.bfs_path((self.robot_pos, self.robot_ori), self.goal)
        self.path_cases = list([x[0] for x in self.path])
        cases = self.path_cases[:]
        self.path_interpolate = []
        for n in (0,1):
            for i in range(0, len(cases)-1):
                if cases[i+1][n] - cases[i][n] > 0:
                    for k in range(cases[i][n], cases[i+1][n]):
                        if n == 0:
                            self.path_interpolate.append((k, cases[i][1-n]))
                        else:
                            self.path_interpolate.append((cases[i][1-n], k))
                else:
                    for k in range(cases[i+1][n], cases[i][n]):
                        if n == 0:
                            self.path_interpolate.append((k, cases[i][1-n]))
                        else:
                            self.path_interpolate.append((cases[i][1-n], k))
        self.path_interpolate = list(set(self.path_interpolate) - set(self.path_cases))
        self.path_cases = list(set(self.path_cases))

app/casshern/grid_creation/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.utils import timezone
from .models import Grid

def index(request):
    return render(request, 'grid_creation/index.html')

def result(request):
    if request.method == 'POST' and request.POST.get('line_size', False):
        N = request.POST['line_size']
        M = request.POST['column_size']
        O = request.POST['obstacle_amount']
    else:
        N = 10
        M = 10
        O = 10
    grid = Grid(line_size=N,
                column_size=M,
                obstacle_amount=O,
                pub_date=timezone.now())
    grid.generate()
    grid.solve()
    grid.save()
    return render(request, 'grid_creation/result.html', {'grid': grid})

app/casshern/grid_creation/templates/grid_creation/index.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col-lg-12">
        <h1>Grid creation</h1>
        <h2>Create your own workspace</h2>
        <form action="{% url 'grid_creation:result' %}" method="post">
        {% csrf_token %}
          <input type="number" name="line_size" id="line_size" />
          <label>How many line you want ?</label><br />
          <input type="number" name="column_size" id="column_size" />
          <label>How many column you want ?</label><br />
          <input type="number" name="obstacle_amount" id="obstacle_amount" />
          <label>How many obstacle you want ?</label><br />
        <input class="btn btn-default" type="submit" value="Process" />
        </form>
    </div>
</div>
{% endblock %}

app/casshern/grid_creation/templates/grid_creation/result.html
{% extends "header.html" %}
{% block content %}
<h1>Grid creation</h1>

<h2>Your workspace</h2>
<table id="grid">
  {% for row in grid.grid %}
      <tr>
        {% for col in row %}
              {% with i=forloop.parentloop.counter0 j=forloop.counter0%}
              {% if col == 0 %}
              <td class="empty">
                <div class="cell-info">
                  {% if grid.robot_pos.1 == forloop.counter0 and grid.robot_pos.0 == forloop.parentloop.counter0%}
                    R <sup>●</sup>
                    <span class="text">({{ forloop.parentloop.counter0 }},{{ forloop.counter0 }})</span>
                  {% elif grid.goal.1 == forloop.counter0 and grid.goal.0 == forloop.parentloop.counter0%}
                    G <sup>●</sup>
                    <span class="text">({{ forloop.parentloop.counter0 }},{{ forloop.counter0 }})</span>
                  {% else %}

                        {% for case in grid.path_cases %}
                            {% if case.0 == i and case.1 == j%}
                                <sup class="dot-path">●</sup>
                            {% endif %}
                        {% endfor %}

                        {% for case in grid.path_interpolate %}
                            {% if case.0 == i and case.1 == j%}
                                <sup class="dot-path">○</sup>
                            {% endif %}
                        {% endfor %}

                  <span class="text">({{ forloop.parentloop.counter0 }},{{ forloop.counter0 }}) <sup class="dot-info">●</sup></span>
                  {% endif %}

                </div>
              </td>
              {% else %}
              <td class="obstacle"></td>
              {% endif %}
              {% endwith %}
        {% endfor %}
      </tr>
  {% endfor %}
</table>

<h3>Grid Information</h3>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Robot
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        Robot position : {{ grid.robot_pos }} <br/>
        Robot orientation : {{ grid.robot_ori }} <br/>
        Robot Goal : {{ grid.goal }} <br/>
        Robot Path : {{ grid.path }} <br/>
        Robot Path (Only Cases) : {{ grid.path_cases }} <br/>
        Robot Path Interpolate (Only Cases) : {{ grid.path_interpolate }}
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          Grid
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
        Grid Column Size : {{ grid.column_size }} <br/>
        Grid Line Size : {{ grid.line_size }} <br/>
        Grid Obstacles Amount : {{ grid.obstacle_amount }} <br/>
        Grid List : {{ grid.grid }}
      </div>
    </div>
  </div>
</div>
<a href="{% url 'grid_creation:result' %}"><button type="button" class="btn btn-secondary btn-sm">Generate new</button></a>
{% endblock %}

app/casshern/grid_creation/templates/header.html
{% load staticfiles %}
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" media="all" href="{% static "grid_creation/simple-sidebar.css" %}">
<link rel="stylesheet" type="text/css" media="all" href="{% static "grid_creation/style.css" %}">
</head>
<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="../">
                        Mobile-Suit-Riders
                    </a>
                </li>
                <li>
                    <a href="#">Create</a>
                </li>
                <li>
                    <a href="#">Archives</a>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
              {% block content %}
              {% endblock %}
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
</body>

<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
<script>
$("#menu-toggle").click(function(e) {
  e.preventDefault();
    $("#wrapper").toggleClass("toggled");
});
</script>